### ISSUE TITLE
Feature request: On the odd chance you'll revisit adding e-mail support

### ISSUE THREAD

**Issue by Alicimurky** [jobisoft/TbSync#103]
## Your environment

TbSync version: 0.7.10
Thunderbird version: 60.0b10 (32-bit)

[ x] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
UBC student e-mail does not support IMAP/POP or SMTP, but it does support ActiveSync on Android. I'd love to read my school mail on Thunderbird (and not super clumsy Outlook.org). Any chance you could revisit the idea of adding e-mail support for cases like these?

https://it.ubc.ca/services/email-messaging/student-alumni-email-service/student-and-alumni-email-faq#imap

## Actual behavior
...

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Hi @Alicimurky,

this at the lower end of my todo list, there is so much other stuff, that needs to be implemented. Furthermore, the work needed to get this done is huge. I am open for Pull Request ("someone else is doing it"), but I do not see myself doing this. 

The syncing part will not be so much work, but the UI, to create a folder in the mails view and make it searchable and fully integrated in Thunderbird. I think the buzzword here is JSAccount and someone who is thinking about implementing this should take a look at ExQuilla - which is about to be discontinued, because adapting it to Thunderbird 60+ is also a lot of work. So this is not really looking good.

**Comment by mikko-ttlsystems** [comment]
Well, hopefully someone gets around to this before October 2020, because that's when some of the older access methods (EWS with Simple authentication, for example) are supposed to get cut off in Exchange Online / Office 365. The language in the announcement isn't all that clear but by a strict reading might also cover IMAP and POP - right now they can be enabled/disabled separately.

(Specific to Office 365 announced plans - other products and services will vary and plans may change.)

**Comment by Alicimurky** [comment]
Thanks for your response, @jobisoft 
I'm afraid this is still veery far from my skill set, otherwise I'd give it a try myself.

**Comment by jobisoft** [comment]
This issue was moved to jobisoft/EAS-4-TbSync#13
