### ISSUE TITLE
Adding repositories for Arch Linux

### ISSUE THREAD

**Issue by jetm** [jobisoft/TbSync#111]
I tried to edit the wiki or submit a PR for documentation changes, but I didn't found the proper way to do it. If there is a way I would happy to do it. 

This is the documentation I want to submit:

_[ COPY FROM HERE ]_
As review Addon process in Mozilla sometimes is very slow, I have created two packages for Arch Linux in AUR repository:

* [thunderbird-tbsync](https://aur.archlinux.org/packages/thunderbird-tbsync/)
* [thunberbird-tbsync-beta](https://aur.archlinux.org/packages/thunderbird-tbsync-beta/)

With `yay` tool either can be installed:
```sh
yay -S thunderbird-tbsync
```
or
```sh
yay -S thunderbird-tbsync-beta
```

**Comment by jobisoft** [comment]
Sadly sending a PR for the wiki is not possible. For one time changes, you can send me the text as you just did, for more complex changes I have to make you a contributor.

But first I got some questions about the content of your changes. How does that work? Do you manage those repositories? The beta may change daily!

Because of the long review times at mozilla, I did already implement a side-channel-updater! If you install the now official version 0.7.10 from addons.thunderbird.net, it will tell you that that there is an unofficial update to 0.7.11 avail, which is currently pending review...

The beta is updated using the same side-channel-updater, users just have to enable the notify4beta options.

You can of course do what you did, I just want to protect you from doing to much work...

**Comment by jetm** [comment]
I only manage to update the packages when I see an update notification either from Thunderbird or from a feed viewer (where I am subscribed to the Atom Github release feed) or someone submits an "out of date" request in the package web page.

The AUR users know what it's submitted in AUR is on their own responsibility. IOW, the user will trust the developer upstream binary files.

I got your point. With the side-channel-updater feature, I guess anyone could update the package, at least for the beta version. But I think it will not work for the stable version where anyone has to wait for the Mozilla review process.

I might not be on track with the beta updates, but I could be on track on the stable updates. The Arch Linux users, like me, could get the "benefit" on getting the update before pass the Mozilla review process.

**Comment by jetm** [comment]
Oh, I see. Initially, I got the impression side-channel-updater feature was only for the beta version. My mistake.
Well, in that case, I don't see right now a utility to keep updating the Arch Linux TBSync packages when you can update the extension using the side-channel-updater feature.

Give me some time to see how it goes with the side-channel-updater feature and following your parsing version suggestion. I will get back to this issue to either ask you to update the wiki documentation or not do it at all :).

**Comment by jobisoft** [comment]
Ok, I keep this issue open. 

You can test the side-channel-updater right now. Install 0.7.10 from addons.thunderbird.net and observe what happens :-)

**Comment by jetm** [comment]
I tested it and the upgrade was OK. I don't see a need to keep updating the Arch Linux packages out of it. You might want to reject this change and close this issue. I will delete the Arch Linux packages as well. Thanks!

**Comment by micwoj92** [comment]
Hi @jetm I know this is really old, but I stumbled across this package on aur and updated it, then I saw this thread and went through aur request mailing list archives from august 2018 to now, but could not find request for removing of that package. Did you fill it in some other way? Feel free to submit request now if you want.
