### ISSUE TITLE
Feature request: Make it possible to disable automatic update check

### ISSUE THREAD

**Issue by michaelweghorn** [jobisoft/TbSync#114]
## Your environment

TbSync version: 0.7.12.3
Thunderbird version: 60.0 

[x] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior

It would be great to have an option to disable the automatic update check as it may be undesirable (in particular e.g. for enterprises) to have the addon connect to servers others than those that hold the actual CalDAV/CardDAV data (e.g. connect to github in the background, "calling home").

In particular when TbSync is deployed via a system-wide installation, there should be no need to check for updates.

## Actual behavior

TbSync automatically checks for updates from time to time (s.a. function `check4updates` in `content/tbsync.jsm`). I could not find an option to disable this.

## Steps to reproduce

* start Wireshark and capture packages on network interface(s)
* start Thunderbird with TbSync being set up and observe what connections are made
* observe connections being shown in Wireshark

**Comment by jobisoft** [comment]
Is an option in the thunderbird config enough, as described here:
https://github.com/jobisoft/TbSync/wiki/Advanced-configurations

**Comment by michaelweghorn** [comment]
Thanks for the super-quick reply!
Yes, in my opinion being able to set an option like this to totally turn off the update check would be enough.

**Comment by jobisoft** [comment]
You can now disable side-channel-update-checks by setting [`updateCheckInterval`](https://github.com/jobisoft/TbSync/wiki/Advanced-configurations/_edit#extensionstbsyncupdatecheckinterval) to zero.

I will release 0.7.14 soon as new stable, which will include this. However, I currently do release often because TbSync is changing and evolving very fast. I added the side-channel-update to get bugfixes to the user, if the review at Thunderbird takes to long.

Furthermore, I do not think it is ready yet to be deployed for use  inside a company. Invites are not yet handled correctly and users need to be aware of the nature of this plugin. If a private user install this on his computer, he probably knows what he is doing. If an employee get presented with a pre-installed TbSync, he might expect to much from it...

Always backup your data!

**Comment by jobisoft** [comment]
Edit: wrong link + typos

**Comment by michaelweghorn** [comment]
Thanks a lot!
And thank you also for your comments with regard to deployment in enterprises. I'm personally just using TbSync as a private user, but think it may become interesting to companies as well at some point in time in the future.
