### ISSUE TITLE
CardBook 30.6 standalone WARNing and (NS_ERROR_FAILURE)

### ISSUE THREAD

**Issue by ovari** [jobisoft/TbSync#116]
## Your environment

TbSync version: 0.7.12.
Thunderbird version: 52.9.1
Operating System: Linux Mint 19

[ ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
No WARNing nor ERROR

## Actual behavior
```
$ thunderbird -cardbook
ExQuilla Configure logging for base
New RotatingFileAppender
Setting up ExQuilla logging to dump for base with level:Config
1535491133768    addons.xpi    WARN    Exception running bootstrap method shutdown on tbsync@jobisoft.de: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIObserverService.removeObserver]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://tbsync/content/tbsync.jsm :: tbSync.cleanup :: line 295"  data: no] Stack trace: tbSync.cleanup()@tbsync.jsm:295 < shutdown()@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/USERNAME/.thunderbird/m6l2h0jj.default/extensions/tbsync@jobisoft.de.xpi!/bootstrap.js:111 < this.XPIProvider.callBootstrapMethod()@resource://gre/modules/addons/XPIProvider.jsm:4968 < this.XPIProvider.startup/<.observe()@resource://gre/modules/addons/XPIProvider.jsm:2924
```

## Steps to reproduce
Run CardBook in standalone mode, i.e. in the terminal type `thunderbird -cardbook`

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
can you retry with latest beta?

**Comment by ovari** [comment]
Thunderbird version: 52.9.1
Operating System: Linux Mint 19
TbSync 0.7.12.4

```
$ thunderbird -cardbook
ExQuilla Configure logging for base
New RotatingFileAppender
Setting up ExQuilla logging to dump for base with level:Config
ExQuilla Configure logging for base
1535532989520	addons.xpi	WARN	Exception running bootstrap method shutdown on tbsync@jobisoft.de: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIObserverService.removeObserver]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://tbsync/content/tbsync.jsm :: tbSync.cleanup :: line 311"  data: no] Stack trace: tbSync.cleanup()@tbsync.jsm:311 < shutdown()@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/USERNAME/.thunderbird/m6l2h0jj.default/extensions/tbsync@jobisoft.de.xpi!/bootstrap.js:112 < this.XPIProvider.callBootstrapMethod()@resource://gre/modules/addons/XPIProvider.jsm:4968 < this.XPIProvider.startup/<.observe()@resource://gre/modules/addons/XPIProvider.jsm:2924
```

**Comment by jobisoft** [comment]
Strange, would you help to understand this?

This version is doing some extra logging. Can you install that, activate debug logging and send me the report after the error occured? Since TbSync UI is not running, you need to find the debug.log in your thunderbird profile folder in the TbSync subfolder. Starting Thunderbird after the error to use the UI to get the log, will reset the log...

[TbSync-beta.xpi.zip](https://github.com/jobisoft/TbSync/files/2331671/TbSync-beta.xpi.zip)

When does that error occur? During start of StandAloneCardBook, or during shutdown?

**Comment by jobisoft** [comment]
I also observed something VERY strange. I am on TB 52.9.1 with lightning 5.4.

If I execute StandAloneCardBook, lightning gets upgraded to 6.2, which causes TbSync to fail (because not compatible). The error you report happens on a line during shutdown, where observers are removed. If Tbsync fails to load during startup, those observers are not added. So this looks plausible.

Could you try to disable lightning on your system and try again?

**Comment by jobisoft** [comment]
should be fixed with this version.
[TbSync-beta.xpi.zip](https://github.com/jobisoft/TbSync/files/2331796/TbSync-beta.xpi.zip)

**Comment by ovari** [comment]
Thank you, TbSync 0.7.12.5 fixed this issue.

```$ thunderbird -cardbook
ExQuilla Configure logging for base
New RotatingFileAppender
Setting up ExQuilla logging to dump for base with level:Config
ExQuilla Configure logging for base
```

Does that mean you will make it available to everyone?

Thank you once again.

**Comment by jobisoft** [comment]
I was just waiting for your confirmation, will push .5 out later
