### ISSUE TITLE
Contacts may be causing Thunderbird to become unresponsive while searching for them

### ISSUE THREAD

**Issue by BillBrowne** [jobisoft/TbSync#121]
## Your environment

TbSync version:0.7.15
Thunderbird version: 60.0 (32-bit)

[X ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
When typing in a contact name, contacts are searched in the background without causing Thunderbird to be unresponsive

## Actual behavior
Typing in contacts in the "To:" field causes Thunderbird to become unresponsive until the list is populated.  
...

## Steps to reproduce
Open a new email
Type contact name into the To: field

I have tried downgrading to 0.7.12, which I do not think had this problem but it still persists - which is why I used "may" in the subject field.  This seemed to only start today when I upgraded to 0.7.15 - I don't think it was like this last week.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
How many accounts do you have added to TbSync? Did you add one recently? 

0.7.12 had auto complete already, 0.7.10 did not. Do you know, if you used 0.7.12 (not released on AMO) before upgrading to 0.7.15?

**Comment by jobisoft** [comment]
Can you confirm, that there is change in behaviour after disbling TbSync in the AddOn Manager?

I really have problems confirming this. The way I coded this should actually prevent this from happening, because my results are added async to the list: The list is populated by whatever Thunderbird is doing as "default" (LDAP, local AB) and parallel to that I make a request to the EAS server and add the results to the list, after I get them. You can actually see that there is a delay before my results are added to the list. They "pop in" later.

So it is not that I "hold up" the process of auto complete, I let it pass as before and add my results as soon as I get them...

Very strange. Sorry that it does not work for you.

Any chance, that gContactSync could be the bad guy?

**Comment by BillBrowne** [comment]
Hi there,
Thanks for that - It was actually the LDAP lookup which was causing the
problem, not TbSync.  Disabling TbSync did not fix the problem but turning
off the LDAP address book did. TbSynk without LDAP is working fine.
I was using these both together with no problems up to today but something
must have changed on our server which is causing ldap to to make
Thunderbird unresponsive.
You can close the ticket.  Cheers!

**Comment by jobisoft** [comment]
Ok, thanks for the feedback.
