### ISSUE TITLE
How to get tbsync to sync automatically

### ISSUE THREAD

**Issue by peter-ward** [jobisoft/TbSync#13]
Hi!

I've recently installed TbSync as a means of updating my two EAS accounts in Thunderbird. However, the only way I can get sync to work is to manually open TbSync (double-click on the TbSync button on the bottom left of Thunderbird) and then to manually click on the "Synchronize this account" button for each one.

Is there a setting somewhere to make syncing automatic or to happen to a schedule? Or is it only possible to sync manually?

Thanks for your help!

**Comment by jobisoft** [comment]
Right above the "Synchronize this account" button is a text input field "AutoSync time in minutes". This is what you are looking for. 

Does that answer your question?

**Comment by peter-ward** [comment]
Yes it, does, thanks. I didn't see any explanation of that in the wiki's getting started page and assumed it indicated how long synchronisation was expected to take. Thanks for your help!

**Comment by mMuck** [comment]
Follow-up on this: I came from the SoGo Connector (CardDAV Sync) and this Add-On synchronizes with an interval too. But if there are local changes made, it triggers the sync right away (and then shows a nice information report like 1 uploaded, 0 downloaded, 0 changed).
If I want to shutdown TB I sometimes triggered the sync manually like @peter-ward described to avoid the delay (and loss until I reopen TB) of the information to the server.
I wondered because TbSync "knows" that there was a local change. Why not doing the sync immediately after a local change?
Perhaps this is a feature request. Thanks :wink:

**Comment by jobisoft** [comment]
That will be nice implemented soon.

**Comment by mMuck** [comment]
:+1:

**Comment by jensconsul** [comment]
The problem of not auto-synching still persists six years later, @jobisoft , unfortunately. 

In the current version of TbSync there is not button or text field for autosyncing, see attached scrngrb.

How do I apply autosyncing?
![Uploading Screenshot from 2024-08-05 17-24-55.png…]()

**Comment by jobisoft** [comment]
I am no longer planing to implement auto-sync on local changes.

**Comment by gza** [comment]
I think I may had the same problem has @jensconsul . I my case, the autosync setup widgets are hidden due to incorrect default size of the window:

https://github.com/user-attachments/assets/e5208e44-3cf0-4434-a2e1-da8a0ebfcd64

**Comment by sopkre** [comment]
> I think I may had the same problem has [@jensconsul](https://github.com/jensconsul) . I my case, the autosync setup widgets are hidden due to incorrect default size of the window:
> Capture.video.du.2025-08-23.08-34-59.mp4

Thanks so much! I was looking for this for a while now...

**Comment by jobisoft** [comment]
The new TbSync Manager lives in a tab and does not have this issue anymore:
https://github.com/jobisoft/EAS-4-TbSync/issues/309
