### ISSUE TITLE
Prevent other AddOns to mess with the card edit dialog of TbSync

### ISSUE THREAD

**Issue by brad2014** [jobisoft/TbSync#179]
Something to think about:

Basic Thunderbird uses an old, rickety way of letting the user specify phone numbers, in that it creates input fields for a fixed set work/home/fax/pager/mobile.  Modern contact lists (vcard-based, google, apple contacts, nextcloud, etc) all let you add as many numbers as you like, and apply a "type" label to each one (so I could have two home phone numbers, for example).

I use gContactSync in TB to pull sync my google contacts.  I recommend its approach.  It replaces the TB phone number list:

<img width="236" alt="image" src="https://user-images.githubusercontent.com/6502462/48666313-112bf700-ea74-11e8-9606-fa0e355d5f9b.png">

with pulldowns for type:

<img width="380" alt="image" src="https://user-images.githubusercontent.com/6502462/48666317-1be68c00-ea74-11e8-8411-7d0809219382.png">

Until we get google sync turned into a tbsync plugin, perhaps we'd consider allowing the two plugins to work well together.  Right now, DAV-4-Sync is rewriting the phone labels, and gcontactsync is supplying the dropdowns, so I get this craziness when I enter a new contact:

<img width="384" alt="image" src="https://user-images.githubusercontent.com/6502462/48666363-c9599f80-ea74-11e8-923e-ef504e289eb4.png">

Notice that the fourth phone number is being labeled Pager, but the dropdown default (which may be in my profile) is Mobile.

My suggestion:  Set the phone labels as "First", "Second", "Third", as in gContactSync, and use pulldowns (ideally, in a way that interoperates with gContactSync).  If the pulldown doesn't exist, create it, and let DAV-4-Sync or EAS-4-Sync populate it with the set of phone number types that they understand.   You can remove all the phone numbers from the `Other Fields (EAS)` form, and simply pick them off the list of the front page, since you've added things like "Radio Phone" to the dropdown list there.

Later, when Google Contact Sync has been added to TbSync, this same approach will work, and be better than creating a new page with the many types of phone numbers google supports.

Note:  Don't forget to update the contact-list add-column pulldown menu to include any new fields you support.  Right now, I can't select any of the new columns for my view, even though they're being added.  Notice that I can't add "Main phone number" here:

<img width="233" alt="image" src="https://user-images.githubusercontent.com/6502462/48666443-00c94b80-ea77-11e8-9258-5a5aafd94dfe.png">

**Comment by brad2014** [comment]
@jobisoft I'm interested in your thoughts as to whether this seems like a bad idea, a good idea, a distant aspiration, inline or contrary to the direction you'd like to take.

**Comment by jobisoft** [comment]
First of all I need to understand, why gContactSync is messing with my contacts edit window. I am not messing with his. Do you remember if that also happens with the sogo-connector? They created their own addressbook type, I may have to do that as well...

From a very first impression, I do not want to change so much of the edit UI. Having numbered fields also does not sound to good to me. I do not want to recreate cardbook, that exists already (and will be usable as sync destination from TbSync). EAS does not have more fields than I added...

I will have to think about that but this is currently not on my agenda.

What I think is useful now and would be happy to get PR or code examples for:
- get my custom fields into the column select menu as you pointed out
- create a custom address book type (with a custom provider icon instead of the "book"?) so other Addon cannot mess up my edit window (if that is the case)

Both is probably better to be implemented in TbSync itself so it can be used by all providers.

**Comment by jobisoft** [comment]
EAS is adding middle name and third email and the extra tabs at the end, DAV is adding Main phone number and a few more I cannot recall right now. But they only add them to their own type, not to others.

**Comment by jobisoft** [comment]
I renamed this issue, because I will only fix the gContactSync AddOn from messing with my card edit window, but I will not add the feauture you request. 

EAS does not allow to specify more phone numbers as allowed via the UI. For CardDAV, you can use CardBook, if you want to use that feature.

**Comment by jobisoft** [comment]
For the last two weeks I tried to get around this issue. 

First I contacted the author of gContactSync and got a nice reply, so we will be able to sort this out. Furthermore, I worked on improving the edit dialog itself. First I allowed multiple emails (which is avail in the latest beta already) and now I also use the same method to allow multiple phone numbers:

![image](https://user-images.githubusercontent.com/5830621/53253645-08c20880-36c2-11e9-91f6-3038dd7c47e6.png)

I did not add this UI to the edit dialog of EAS accounts, since they only support a fixed number of fields, which are already avail in the UI. For CardDAV however, the new UI allows to add "a rather large number" of phone numbers and email addresses.

**Comment by brad2014** [comment]
Incidentally, the UI you've designed looks fantastic, IMHO.  👍

**Comment by jobisoft** [comment]
I just released all that as the latest beta. If you want to give it a try :-) As mentioned earlier, that UI is only activated, if the selected address book is a CardDAV address book.

I also updated the details view:

![image](https://user-images.githubusercontent.com/5830621/53273200-a255de00-36f3-11e9-8db6-6dca6833dfc2.png)

To install the beta, follow the instructions given here:
https://tbsync.jobisoft.de

Feedback is appreciated!
