### ISSUE TITLE
Feature request: Create birthday calendar from addressbook

### ISSUE THREAD

**Issue by metlinux** [jobisoft/TbSync#207]
I was hoping you might consider adding the following feature to tbsync:
Add the (selectable) option _"create birthday calender from addressbook"_ in tbsync.

This option should create a seperate calendar in lightning from the birthdays that are registered in the addressbook and keep it in sync

I know this functionality will be enjoyed by many, and I think it would fit perfectly in tbsync, since it has access to both Lightning as well as the addressbook.

Many people would like to see the birthdays they register in their addressbook in their calendar as well, ideally with a reminder so they won't forget. Currently it does not show within the calendar in lightning. Of course since the calendar is caldav and a different source it is no real suprise it currently doesn't.
But with tbsync we could, with a seperate calendar. You could even calculate the age along with it.

Apple IOS does a similar thing where birthdays from carddav end up in your calendar stating the contact name and it's age:
   e.g. _"John Bieling's 31st Birthday"_ (the age will probably be incorrect ...)

I hope you like the idea and might consider adding this feature.

**Comment by metlinux** [comment]
That would also deliver the functionality, indeed, but I would prefer to have this central in one solution: TBSync, instead of seperate tools. It would simplify the setup and makes more sense to have just one add-on in the middle who synchronizes information with Thunderbird.

But I would understand your decision of course

**Comment by jobisoft** [comment]
I let it sit here with "help wanted", which basically means, "someone else has to do it". After my looooong todo list is cleared, I might return to this.

**Comment by chdoc** [comment]
Hi, I just want to mention that [ThunderBirthDay](https://addons.thunderbird.net/en-US/thunderbird/addon/thunderbirthday/) does not work with Thunderbird versions greater than 60, so I want to second this feature request. Indeed, the current [list of results](https://addons.thunderbird.net/en-US/thunderbird/search/?q=Birthday&appver=68.2.1&platform=linux) for "Birthday" does not look very promising.

The Thunderbird address book already displays birthday and age separately, so an auto-generated calendar with some configurable string with a few variables (first name, last name, year of birth, age at birthday) should not be too hard to implement. On the other hand, this might just as well be a feature of lighting, since it doesn't actually depend on syncing ...

**Comment by jobisoft** [comment]
This will help you for TB68:
ingomueller-net/ThunderBirthDay#11 (comment)
