### ISSUE TITLE
Contact sync error when SOGo sends Picture as URL instead of inline binary

### ISSUE THREAD

**Issue by Mati24** [jobisoft/TbSync#236]
## Your environment

TbSync version: 1.5
Thunderbird version: 50.5.0

[ ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Synchronisation of contacts

## Actual behavior
The synchronization failed on 
(xxxxx, xxxxëxx) <xxxxxxx@xxxxx.xxxx>
```
JavaScript Error 

Failed to decode base64 string!

addphoto@chrome://tbsync/content/tbsync.jsm:1490:26
setThunderbirdItemFromWbxml@chrome://eas4tbsync/content/provider/eas/contactsync.js:208:13
eas.sync.processCommands<@chrome://eas4tbsync/content/provider/eas/sync.js:548:25
TaskImpl_run@resource://gre/modules/Task.jsm:326:42
TaskImpl_handleResultValue@resource://gre/modules/Task.jsm:408:7
TaskImpl_run@resource://gre/modules/Task.jsm:334:15
```

## Steps to reproduce
Accent in the name of a contact, example ë

**Comment by jobisoft** [comment]
Thunderbird 50.5?

**Comment by Mati24** [comment]
60.5 sorry

**Comment by jobisoft** [comment]
Are you sure this is related to the name of the contact? The error happens when he tries to decode the photo of the contact.

I added some debug output to the latest beta:
https://tbsync.jobisoft.de

Can you enable debug logging (under help in the tbsync manager) and try again with the beta? It will still fail but the error log might contain useful information. After it failed, send in a bug report (under help in the manager)

Thanks!

**Comment by Mati24** [comment]
Yes it seems to be the decode of the photo, I have it with an other contact 
`Failed to decode base64 string!

addphoto@chrome://tbsync/content/tbsync.jsm:1513:26
setThunderbirdItemFromWbxml@chrome://eas4tbsync/content/provider/eas/contactsync.js:208:13
eas.sync.processCommands<@chrome://eas4tbsync/content/provider/eas/sync.js:567:25
TaskImpl_run@resource://gre/modules/Task.jsm:326:42
TaskImpl_handleResultValue@resource://gre/modules/Task.jsm:408:7
TaskImpl_run@resource://gre/modules/Task.jsm:334:15`

**Comment by jobisoft** [comment]
The latest beta dumps the string (which fails) into the debug log (not the error log). If you get this error with the beta, go to help and click on "create bug report", which wills end the debug log to me.

Thanks

**Comment by jobisoft** [comment]
The PICTURE may not be an URL
https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-ascntc/ac4faa8f-b959-4190-9cdc-d787e1717dfb

What kind of server is doing that?

**Comment by Mati24** [comment]
SOGo

**Comment by jobisoft** [comment]
Which Version? They just released a new one. Are you subscribed to the sogo mailing list?

**Comment by Mati24** [comment]
I had 4.0.5.20190216-1, I just upgraded to 4.0.6.20190227-1 but same error :(

**Comment by jobisoft** [comment]
Can you poke around a bit, if that behavior can be changed via configure options? I found a commit regarding photo support via EAS which does look like base64 encoded inline files...

Otherwise you have to create a bug report at soho or at least get someone to explain, why the go off the spec.

Is there any other client, which supports that?

**Comment by Mati24** [comment]
I'm not sure it's a SOGo problem. Actually, I have contacts with an url in the picture data, that I inherit from my migration from Google Contact, which get the picture from Google Plus...
On my phone, the picture shows normaly, but on the SOGo WebApp, I don't see the picture...
So I have to cleanup my contacts picture.
Sorry for the trouble

**Comment by jobisoft** [comment]
You did not cause trouble. The error itself was reported correctly: TbSync should be able to handle unexpected userdata instead of failing.
