### ISSUE TITLE
Text from some Fields is not selectable in the adressbook

### ISSUE THREAD

**Issue by dagaz** [jobisoft/TbSync#266]
## Your environment

TbSync version: 1.7
Thunderbird version: 60.8.0 (64 Bit) (Arch Linux)

[X] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
When I open the adressbook and select a name and then select contact information on the detail sheet (like Adress, e-mail-adress, phone number) the text should be selected so that i can copy it to the clip board.

## Actual behavior
Text from some fields is not selectable. Copying phone number and e-mail-adress is not possible. I have to edit the contact, where i can copy the informations. I think that is very cumbersome.
But Text from other fields is working as expeded, like adress or categroies. 

## Steps to reproduce
Try to copy phone number or e-mail-adress directly from the adressbook without editing the contact.

**Comment by jobisoft** [comment]
Current development has switched to Thunderbird 68 (Beta). I fixed this issue as much as I could in the latest beta of for TB68.

Details about the beta release channel:
https://tbsync.jobisoft.de

I cannot make the email copyable, because it is a link (now). All other fields should be copyable.

Closing this to have it out of the way. You can still post.
