### ISSUE TITLE
Self-Signed Certificate is not accepted

### ISSUE THREAD

**Issue by Khymick** [jobisoft/TbSync#282]
## Your environment
Windows 10

TbSync version: 2.4
Thunderbird version: 68.1.0 (64-Bit)

[x] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Connection to a CardDav server with self-signed certificate should work.

## Actual behavior
Connection to CardDav server with self-signed certificate fails with error message ("are you using a self-signed certificate...")

## Steps to reproduce
1. Install all necessary Tbsync packages

2. Follow https://github.com/jobisoft/TbSync/wiki/How-to-use-TbSync-with-self-signed-or-otherwise-untrusted-certificates%3F to add exclusion for server
I am using the following settings:
exclusion in Thunderbird: 
- Server address: https://my.server.net:8843
(I have to use this port, as when I only use the address without port, Thunderbird says that this server gives out a valid certificate). Problem behind may be that behind my URL, there are 2 servers with different certificates. The URL itself has one from letsencrypt, the server with the carddav has another one.

3. Add account in tbsync

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Synology? what is the excaxt reason for the bad cert (below the human readable text) REVOKE?

**Comment by Khymick** [comment]
No, the carddav server is located on a Mac Server.
The reason is "SEC_ERROR_UNKNOWN_ISSUER".
It cannot be a revoke, as the connection to the carddav server is perfectly running from other systems (eg a linux client with evolution).

**Comment by jobisoft** [comment]
ok, synology had an error last week, where it issued that message and I had dozens of those reports, so it was worth a try.

I have not fully understood your issue. You said you added an exclusion for your cert? But why does TbSync still complain?

> (I have to use this port, as when I only use the address without port, Thunderbird says that this server gives out a valid certificate

I do not understand that. You of course have to use the port which provides the service you want to use.

**Comment by Khymick** [comment]
I will try to explain a little bit deeper.
All services I am using are available via a DynDNS address. My router is directly a client of this DynDNS address. On the router, I have made quite some port forwardings. Some of them are going to server A, some of them to server B. Server A has its own certificate, while server B has other ones.

Server B is a Mac Server. Here, I forwards the ports for carddav on the router. The certificates on this server were automatically created while installing the Mac Server App.

Now, I am trying to connect Thunderbird to my Mac Server (because carddav is available here). When I give only the DynDNS address without ports, it seems that Thunderbird tries to connect to server A (that is my understanding), because Thunderbird says that the server is answering with a valid certificate - this can only be the cause if it gets the certificate from server A, because this one is delivered by Letsencrypt. The certificate from server B (=Mac Server) are self-created.

I do see a problem here, because I cannot seem to tell TBSync to use the certificates of server B. Or am I wrong here? And/or is this related to the problem?

If you need more infos, please let me know.

**Comment by jobisoft** [comment]
I do not know your current level in the working-with-certs-game, so please excuse if some of this is already known:

- certs do not certify a port, just the name like "mycloud.server.org"
- if a https connection without port is opened, the default port 443 is used - check your port forwarding rules where port 443 is going to see which of your serves is answering the request. You could also inspect the returned certificate to see what it contains (lets encrypt or self signed)
- there is a small chance, that your router does not allow (or ignores) forward requests for port 443 and answers these by himself, inspecting the returned cert should answer this.

- if you want to add an exception in Thunderbird for your self signed cert, you need to use `https://host:port` because Thunderbird is actually requesting the cert from that server and stores it and you tell him (after inspecting the downloaded cert) YES, I DO TRUST THIS CERT and from then on, Thunderbird will trust it.

Did you really add an exception for the same value as you use in TbSync?

Is your server reachable from the internet? Could you send me the url in private?

**Comment by Khymick** [comment]
Concerning certs: Yes I know some details ; I just stumbled over the way Thunderbird is working here. I never had problems with the certs so far.

I could give you the url in private ; how should I send you the info?

**Comment by jobisoft** [comment]
My email is listed on my main gitub page

**Comment by Khymick** [comment]
Mail sent.
