### ISSUE TITLE
Upgrading to Thunderbird 68

### ISSUE THREAD

**Issue by ohmer1** [jobisoft/TbSync#314]
Hello,

I'm planing the upgrade of Thunderbird and TbSync in our company. I read the upgrade instruction at UPDATE68.md. Is there a way to automate that in a deployment script? I fear that the upgrade will broke my users' configuration by reading this documentation. :(

**Comment by jobisoft** [comment]
You mean, that you can somehow trigger the ‚disable‘ function from the outside? I do not think that is possible. The user has to do it, because he needs to sync first.

**Comment by ohmer1** [comment]
Well, this make things complicated in a company when the software deployment is automated and doesn't require user's action. I'll need to upgrade thunderbird and tbsync manually on each desktop. I hope this doesn't occurs too often.

**Comment by jobisoft** [comment]
I had so much hassle with the changes for TB68, that is just insane. I am glad the whole thing did not explode. I did not spend more time than needed on the upgrade stuff. If you really need some advanced migration, than I need to add a lot of code. You would need to pay me by the hour. It is not impossible.

The current status is: If you do not do any preparations, than TbSync will disable/disconnect all accounts on upgrade and will add a big red exclamation mark to all old (disconnected) resources. All accounts are disabled and the users have to enable them again, starting a fresh sync. Any local changes which have not been synced still exist in the disconnected resources.

What do you need to be automated?
 - enable all accounts again?
 - compare old and new resourced?
 - merge differences?

Merging changes is error prone and this will need a lot of concentration and the chance I will mess that up (and the user data) are extremely high.

**Comment by ohmer1** [comment]
Not sure, but if I understand well, if the configured accounts in previous version can be automatically enabled after upgrade, you don't need to compare old/new resources and merge differences.

**Comment by jobisoft** [comment]
The issue is a follows:
 - internal presentation of data has changed from TB60 to TB68
 - I do not have code to transform existing TB60 data to TB68 data
 - I ask the user to sync everything to the server before upgrade, so all data in on server
 - I ask user to disable all accounts in TB60, which removes all local data 
 - user updates
 - user enables accounts and gets all his data back, saved localy in TB68 format

Just enabling accounts does not help. I asked user to disable, so we do not have any old data flying around. If the user did not disable prior to upgrade, I disable the accounts manually after the upgrade and mark all local data/resources as deprecated/disabled (red exclamation mark).
