### ISSUE TITLE
EWS support how far out

### ISSUE THREAD

**Issue by afettouhi** [jobisoft/TbSync#320]
This is not a bug report but more of a question. Is EWS support still being planned for this extension. I am looking for support for seeing shared calendars as mentioned in this closed bug report here:

https://github.com/jobisoft/TbSync/issues/16

How far out is this feature from being added?

**Comment by jobisoft** [comment]
The ongoing changes in TB slow down development.

For TB78 (Summer 2020) I try to get TbSync into Thunderbird, so that contacts and calendars of remote accounts are discovered automatically during standard (email-)account setup. The TbSync addon would not be needed anymore, but its provider interface will be a fixed part of Thunderbird. The EAS and the DAV provider will continue to work and other authors can add more providers.

The developer of [owl](https://addons.thunderbird.net/addon/owl-for-exchange/) is currently working on OWA/EWS support and thus I no longer put time into that. My personal believe is, that the original EWS calendar plugin is to old to be able to be adapted to modern Thunderbird, so a rewrite is needed anyhow, just like owl is doing that now. The author of owl will probably use the new contatcs/calendar interface, once it is in.

I believe owl has calendar support as of now. Ask its developer, if you struggle to set it up.

Hope this helps.

**Comment by afettouhi** [comment]
So the owl plugin is an alternative to yours or add-on to it?

**Comment by jobisoft** [comment]
I would not call it an alternative as we do different things. 

TbSync together with its Exchange ActiveSync provider uses the Exchange ActiveSync protocol to sync contacts, tasks and events. Owl uses OWA and Exchange WebServices, which are different protocols.

But yes, if Owl works for you, you do not need TbSync and its ActiveSync provider.

**Comment by afettouhi** [comment]
Thanks for the clarification.
