### ISSUE TITLE
View / sync shared calendars from other users

### ISSUE THREAD

**Issue by ontheair81** [jobisoft/TbSync#356]
TbSync version: 2.9
Thunderbird version: 68.4.1

[x] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

Hello, I just installed TbSync along with Provider for Exchange ActiveSync and connected to the Exchange server of my company. Everything works fine and my calendar is synced.

The only question is: There are additional calendars that have been shared by other users for me (I can see and edit them in Outlook Web Access for example).
How can I sync these calenders in Thunderbird, additionally to my personal calendar? Right now they are not visible in Thunderbird, just my personal one.

I was not able to find anything about that in the documentation (did I miss something?), so a hint would be highly appreciated!

Thank you!

**Comment by jobisoft** [comment]
Sadly, that is not possible, because TbSync uses EAS (Exchange ActiveSync) to connect to your exchange server and that protocol does not support shared calendars. Only recently Office 365 started to populate personal shared calendars via EAS but not globally shared.

For shared calendars (and much more business features) you need the "bigger brother" EWS (Exchange WebServices), which I currently have no time impl.

**Comment by ontheair81** [comment]
Ok, thank you for your help and for pointing this out!

**Comment by sascha-wi** [comment]
Is this still the current status?
