### ISSUE TITLE
Handling of meeting invitations

### ISSUE THREAD

**Issue by Nico321** [jobisoft/TbSync#46]
Hi,

Im missing the description of some of the meetings. It appears, that I can see the description for meetings which I created myself, but im missing the notes for meetings, which i got invited to.

This is what a meeting looks like, which I was invited to:
![image](https://user-images.githubusercontent.com/6123294/35807483-39689b1e-0a83-11e8-907c-f2830e07983b.png)

This is an example of a meeting, which I created myself (notice the tabs for description, attachments and participants):
![image](https://user-images.githubusercontent.com/6123294/35807421-03dea63c-0a83-11e8-99f5-de4b85f1fc10.png)

Im using Thunderbird 52.6.0 (64-Bit) on macOS High Sierra 10.13.3. Descriptions are available for all meetings when using CalDav or ActiveSync on iOs.

If you need any further information, feel free to contact me.

**Comment by jobisoft** [comment]
I think this is a limitation of Thunderbird. The Invitation dialog does not display the description.

But handling invitations itself (accepting, declining,..) is not yet fully supported by TbSync. I keep this issue open until I made progress on this.

**Comment by mdwy62** [comment]
When I try to set up a meeting and invite attendees, I am asked to send emails and I select yes. Everything looks fine on my end, the event is added to my calendar, but no invitees receive the email invitations. I am using Thunderbird 52.7.0 on Ubuntu 16.04. Is the ability to invite others over EAS supposed to work or is it not supported currently? Thanks.

**Comment by jobisoft** [comment]
Handling invitations (accepting, declining,..) is not yet fully supported by TbSync. On some systems it works, on some it does not. I have not yet found the reason. This might take some time...

**Comment by crbble** [comment]
In my experience TbSync calendars behave like local calendars, which is also why Thunderbird asks to send E-Mails to the attendees (it does not do this for CalDAV events). If this does not work, it is a general local Thunderbird problem (like your hint about the calendar and e-mail address association, which may be checked in the calendar settings). 

All other behaviour will be ruled out by the server and most likely all servers will behave differently. Horde has been messing around with this using CalDAV since several years (for example bugs 3965, 13664 in the horde bugtracker). Problems are the changing of the event owner, modification of the event on every acceptance and others.

**Comment by jobisoft** [comment]
That is correct, I have not yet created my own calendar type, but use the "local calendar type". To fix this issue I eventually have to create my own type so I can control how these emails are send. 

But I will start working on this only after all other non-calendar issues are solved and TbSync is stable.

**Comment by jobisoft** [comment]
This issue was moved to jobisoft/EAS-4-TbSync#10
