### ISSUE TITLE
Avoid unrestricted access to Thunderbird

### ISSUE THREAD

**Issue by martenlehmann** [jobisoft/TbSync#564]
## Your environment

TbSync version: 3.0.1
Thunderbird version: 91.5.1

## Expected behavior
I'd like Thunderbird and its extensions to work only with the permissions they need for their job.

## Actual behavior
Upon adding this extension, Thunderbird asks to get permission to "[Have full, unrestricted access to Thunderbird, and your computer](https://support.mozilla.org/en-US/kb/permission-request-messages-thunderbird-extensions#w_have-full-unrestricted-access-to-thunderbird-and-your-computer)" which is quite scary, especially considering the detailed info at the knowledge base.

## Steps to reproduce
Click on "+ Add to Thunderbird" on this extension.

The KB describes that extensions "using an older technology" require this permission, but as TbSync is being updated constantly, shouldn't there be less threatening ways?

**Comment by jobisoft** [comment]
> The KB describes that extensions "using an older technology" require this permission, but as TbSync is being updated constantly, shouldn't there be less threatening ways?

Yes, but currently I do not have the time to rewrite the extension.

For the record: The add-on was using the same "full access" since it first release. But in TB78 - when the new permission based system was introduced - it was changed to notify the user about that. So nothing changed. This add-on is still subject to human review before it is distributed via ATN.

The new permission system will allow for faster reviews, as not all extensions have to be reviewed anymore, since the permission system restricts them in what they can do.
