### ISSUE TITLE
TbSync keeps asking to install EAS sync provider which IS already installed

### ISSUE THREAD

**Issue by sispli** [jobisoft/TbSync#622]
## Your environment: Windows 10 Pro 64 bit

TbSync version: 4.3
Thunderbird version: 102.4.0
EAS version: 4.15

## Expected behavior
In TbSync I should be able to setup a Microsoft e-mail account that contains my contacts.

## Actual behavior
TbSync throws up an error message, telling me to install the EAS sync provider which is already installed (see screenshot).

## Steps to reproduce
not applicable.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).
![Error](https://user-images.githubusercontent.com/57145629/197346776-d8a29d69-dc09-4de8-a2ff-812279422673.jpg)

**Comment by jobisoft** [comment]
I really hope someone can spot an error on the error console when this happens. I have never observed this and don't know where it is coming from.

**Comment by saulotoledo** [comment]
I installed Thunderbird today on Linux and installed TbSync for the first time. I installed the extension, and I had the same error. I noticed that the issue happened to both "Exchange ActiveSync" and "CalDAV "CardDAV" accounts.

Then, at some point, I restarted the application and saw a message "...to use this extension update Thunderbird to 102.3.3", but the last version available to install in my system is "102.3.1". The strange part is that the Mozilla extensions website installs the last version, even if incompatible.

I went to https://github.com/jobisoft/EAS-4-TbSync/releases and downloaded a previous release (the XPI file is available for each release). Then I installed it from the XPI file, and the application is working now.

I believe the reason for not having anything in the logs is that the problem is with the providers' extensions and Thunderbird itself, allowing those extensions to be installed even if incompatible. I do not know much about those extensions' development, so I can't help much here. But I hope this information helps you to solve the problem.

**Comment by jobisoft** [comment]
Using pre releases can cause data loss. You are using a TB version which has a bug which eats your categories, that is why I officially do not support it. Update thunderbird to 102.4 (current official release)

**Comment by saulotoledo** [comment]
Thanks for the note, @jobisoft. I will try it soon, but the new version is not officially available in the Linux distro repositories yet, so I have to do it manually (which might be painful) or wait until the distro upgrades the package...

**Comment by jobisoft** [comment]
Snap may be an alternative, if you distro maintainers are so lazy and let you use broken versions:
https://support.mozilla.org/en-US/kb/installing-thunderbird-linux#w_install-from-snap

**Comment by sispli** [comment]
I can fully confirm this erratic behaviour as reported by Krisseck

**Comment by jobisoft** [comment]
When this happens next time, is it enough to disable and re-enable TbSync (and not doing a full restart)?

And does it really break after it has already been working, while Thunderbird kept running (without hibernation or other shutdown-like actions)?

**Comment by sispli** [comment]
Yes, disabling and then enabling Tbsync does fix the error.

And it never breaks when it starts correctly (without the error) after firing up TB. The problem only happens sometimes (!) when TB is fired up and Tbsync throws up the error immediately.

**Comment by jim-davenport** [comment]
The only other extension I have installed is Dark Reader - in case that helps.

**Comment by IpeTek** [comment]
For me disabling uBlock Origin seems to have solved the problem.

**Comment by cotsuka** [comment]
@jobisoft I believe timing is the issue here. I have no other add-ons installed and simply disabling then re-enabling either TbSync or the EAS Provider will get it to correctly pickup it's existence. I will note that I have this issue every time I startup Thunderbird, unlike @sispli.

**Comment by jobisoft** [comment]
My x-mas vacation was used up by updating my CategoryManager add-on. I will look at this issue as soon as time permits, sorry for the inconvenience.

**Comment by Mr-nUUb** [comment]
It happens to me, too. Looks like a timing issue / race condition, because sometimes it's fine, sometimes it's broken. What fixes it: either disable and enable EAS provider or disable and enable TbSync. Both ways work.

Also affects CalDAV & CardDAV Provider.

TbSync: 4.3
Thunderbird: 102.7.0
EAS Provider: 4.1.5
CalDAV & CardDAV Provider: 4.3
OS: Arch Linux (updated today, 27-01-2023)

**Comment by jobisoft** [comment]
I have this on my radar, but no time currently. I am very sorry for the inconvenience.

**Comment by jobisoft** [comment]
I think this has been fixed. Reopen, if that is not the case.
