### ISSUE TITLE
caldav.calendar.yahoo.com authentication fail

### ISSUE THREAD

**Issue by Xagec** [jobisoft/TbSync#666]
## Your environment

TbSync version: 4.3
Thunderbird version: 102.10.1

## Expected behavior
Read and write access to personal Yahoo calendars

## Actual behavior
Thunderbird/Yahoo would not accept my username and password, and the added calendars can no longer be enabled 
## Steps to reproduce
...

After having the same issue in late Dec, I installed TbSync and Provider for CalDAV & CardDAV, and that took care of it for awhile. Then, a few weeks ago (after the previous to 102.10.1 TB update?), the problem returned and have stayed ever since. I tried removing and re-installing both add-ons, and then today updating Mozilla to the latest version, all to no avail. Additionally, the directly added to Thunderbird, read-only, calendars, periodically get disabled so I am guessing the issue is on Yahoo's side. Any suggestions would be highly appreciated, I need access for work and on a daily basis. 

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by davidmybox** [comment]
I am having the same issue.
![image](https://github.com/jobisoft/TbSync/assets/133148581/ae82dd0f-df53-4b24-ac43-051e92ce2dd5)

**Comment by jobisoft** [comment]
I only updated my CardDAV provider for tb102 because some people asked for it. But Thunderbird 102 now supports cardav nativly. Can you try if it finds your address books on its own? (In the Thunderbird address book, you can now add carddav address books)

**Comment by davidmybox** [comment]
Thank you John.   Yes you are correct, but the CardBook has an "Events" field feature that I need.  Would it be too much to add this to the TB address book? - Regards David





| 

 | 
 |

  

    On Wednesday, May 10, 2023 at 11:43:18 AM PDT, John Bieling ***@***.***> wrote:  
 
 


I only updated my CardDAV provider for tb102 because some people asked for it. But Thunderbird 102 now supports cardav nativly. Can you try if it finds your address books on its own? (In the Thunderbird address book, you can now add carddav address books)
