### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by franklupo** [jobisoft/TbSync#67]
Hi,
How can I create a translation in Italian?

best regards

**Comment by jobisoft** [comment]
Thanks for your offer! The language files are here:
https://github.com/jobisoft/TbSync/tree/master/locale/

First, fork the project. Then - in your copy of TbSync - copy the en-US folder to it-IT and update the translations in the 4 files. After you are done, create a pull request and I merge your new translation. 

If forking and doing a pull request is to difficult, just send me the 4 italien files and I add them to the project.

**However, I would ask you to wait a few days, because some parts of TbSync are not yet localized, but the english text is hardcoded (most of the manager). I would like to change that first and will tell you when I am done?**

**Comment by jobisoft** [comment]
I am done. You can now clone the project, and update the files in locale/it-IT. If you have questions, just ask.

Thanks for your offer to help!

**Comment by franklupo** [comment]
Hi,
my friend https://github.com/Corisnvest/TbSync translate this for you.

best regards

**Comment by jobisoft** [comment]
Thanks, i am closing this issue than and wait for the pull request. If yiu friend hascquestion, he can reopen this issue or just email me.
