### ISSUE TITLE
Events go missing (though they exist in the database). Entire Calendars go missing too sometimes

### ISSUE THREAD

**Issue by EG19** [jobisoft/TbSync#721]
## Your environment
TbSync version: 4.8 (+Provider for Exchange ActiveSync: 4.8)
Thunderbird version: 115.10.1 (64-bit)
Calendar data stored at outlook.com

## Expected behavior
Steady display of calendars and events.

## Actual behavior
1. Some events are missing in Thunderbird although they exist at Outlook.com. When I modify these events (very slightly) at Outlook.com they may re-appear in Thunderbird.
2. Thunderbird “forgets” entire calendars from time to time. When this happens, TBSync seems to be running as usual but the “Account Settings” section (in TBSync) is empty, i.e all pre-configured settings are lost.

## Steps to reproduce
I do not know what causes this and don’t have a clue how to reproduce. I do not know how many events are currently missing in Thunderbird, but I find such instances occasionally.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by simonflutilliant** [comment]
I have the same problem here, and it seems to be linked with loosing connection, specially on a laptop.

**Comment by smalone-mts** [comment]
I use TbSync to sync an office 365 account.
When I accept a new meeting invitation it gets added to my calendar locally with no issue. 
Then when TBSync syncs it seems to be erasing the entry.

I see an entry in the Event log:
Change request from server, but also local modifications, server wins!

Below that I see: 
Sync.16
Account: <ACCOUNT NAME>
Resource: Calendar

**Comment by schor123** [comment]
Can confirm this behaviour. All Outlook Calendars disappear from one minute to the other, although it has been working for weeks/months before. No way to sync existing events on exchange back to Thunderbird. Re-installing tbsync/active sync or re-adding calendars doesn't help: Existing events stay on the outlook/exchange servers and aren't synced. Newly created events get synced though. No clue what's happening here. Renders TBsync useless at the moment. Existing google-mail calendars work are synced though (although not using tbsync).
Already filed a bug-report (debug.log) via the plugin and urging for feedback/resolving this issue here. Thx.

**Comment by jobisoft** [comment]
This is reported against Thunderbird 115 and TbSync 4.8 + EAS 4.8.

Do you also experience this with Thunderbird 128 and TbSync 4.11 + EAS 4.12 ?

**Comment by schor123** [comment]
Can confirm on TB 128.2.0esr (64-bit)
as well as on TBSync 4.11 & Active Sync Exchange provider 4.12. 
Please suggest a solution thx.

**Comment by jobisoft** [comment]
https://github.com/jobisoft/EAS-4-TbSync/issues/266
