### ISSUE TITLE
Multiple calendars don't show up

### ISSUE THREAD

**Issue by naevtamarkus** [jobisoft/TbSync#87]
## Your environment

TbSync version: 0.7.7.21
Thunderbird version: 52.8.0 64-bit

[X] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
I expect to see my previous events

## Actual behavior
I don't see any events that already existed in my calendar before using this module. I can see, though, new events that I create with this module, which in turn I see when I connect to OWA from the browser.

## Steps to reproduce
Just install and configure normally

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

I see this repeat again and again:
```
** Thu Jun 07 2018 18:09:35 GMT+0200 (CEST) **
[JavaScript Error: "TypeError: prefService.getBoolPref is not a function" {file: "chrome://exchangecommon/content/priority-display.js" line: 40}]
gBP@chrome://exchangecommon/content/priority-display.js:40:12
_execute/extrasObserver.observe/columnHandler.getRowProperties@chrome://exchangecommon/content/priority-display.js:145:42
```
I don't see anything else in the log, other than this in the beginning:
```
** Thu Jun 07 2018 18:08:58 GMT+0200 (CEST) **
[calendarObserver::onLoad] : <Me CalDAV> was loaded.
```

**Comment by jobisoft** [comment]
exchangecommon is not related to TbSync.

I have heard (but not seen) the behavior you are describing a couple if times by now. I *think* the missing items will show up in a few days. What kind of server are you connecting to?

What I assume: Some servers wait till a few (new) items have been synced back and forth before sending all the old items to TbSync. Maybe because they do not know this client.

What you could do: Create a log containing the initial sync
 1. Disable the account in the TbSync Account Manager
 2. Make sure, logging is enabled
 3. Restart Thunderbird
 4. Enable your account

The log now contains the (partially anonymous) log of your initial sync. If your items do not show up there, the server is not sending them, even though I ask for them.

**Comment by naevtamarkus** [comment]
Thanks for looking into this. I am having difficulties with the Ericsson's plugin (and its new fork) and I'm hoping your module could be the solution.

I actually managed to sync the calendar! Did not do much, only found out that the sync was in "warning" state and, after re-syncing manually, all my events started to show up. So far so good (would be nice to see the yellow triangle in the main calendar screen, not having to go into the TbSync window to realize there is something wrong... but anyway), this is already a great improvement. 

My next problem is that I can't see people's calendars. Whenever I organize a meeting and add participants I can see my co-workers availability, but not with this plugin. This is kind-of fundamental to me, I have to admit.

I don't know if this is related, but another missing thing I found is that I could not select the "calendar" or "calendars" I want to sync with: I actually pull from 4-5 different calendars from the same account (events, meeting rooms, and so on), which I can't with this plugin. I would say this is second priority for me, though... 

Do you have a "TODO" list that I can look at, so that I don't bother you about issues you already know?

Thanks a lot! This is very promising (and very well needed around here)

**Comment by jobisoft** [comment]
I received your log. If you look into it and search for "estimate", you can see that your server is not sending anything. Didn't you say, that new items do get synced, so that after a fresh initial sync, these new items should show up? I have no idea what is going on.

You could try to play with this advanced setting:
https://github.com/jobisoft/TbSync/wiki/Advanced-configurations#extensionstbsynceassynclimit

**Comment by jobisoft** [comment]
Oh, i just saw https://github.com/jobisoft/TbSync/issues/87#issuecomment-395668923

I am sorry, but TbSync is using the Exchange ActiveSync Protocol (EAS), which is not the same as Exchange WebServices (EWS). EAS does not support most of the professional features, like shared calendars. They are simply not anounced via EAS.

https://github.com/jobisoft/TbSync/wiki/What-about-access-to-shared-calendars-via-EAS%3F

There is nothing I can do about that. The plugin you referred to is using EWS. I suggest you get in touch with its developer to fix the issues you encountered. From what I can see, you definitly need EWS.

**Comment by naevtamarkus** [comment]
Oops! Ok, I did not know that there were two protocols.
Thanks a lot for the quick support anyway, I will try again with the other module

**Comment by naevtamarkus** [comment]
Sure, please do. No worries!
