### ISSUE TITLE
[Zoho] I  have multiple calendars under my account, but they are not shown/available via TbSync

### ISSUE THREAD

**Issue by freedriven** [jobisoft/TbSync#89]
## Your environment

Ubuntu 18.04
TbSync version: 0.7.7.28 
Thunderbird version: 52.8.0

[X ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
I have a Zoho account, within which I've created multiple calendars (eg 'username', 'moonlighting'). I would expect the option to view and sync any/all calendars in that single Zoho account.  I'm syncing via msync.zoho.com.
## Actual behavior
In TbSync, only my main 'username' Zoho calendar is available. I've tried deleting and resyncing.
## Steps to reproduce
Simply create and sync a Zoho account via msync.zoho.com

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Could you send me a screenshot of your account manager after sync? Something like this, so I can see the available folder?

![image](https://user-images.githubusercontent.com/5830621/41355820-a84eb88e-6f22-11e8-8e8e-5797f94d455d.png)

If this would reveal to much information, send it via email.

**Comment by freedriven** [comment]
Here you go, with only my account name and domain name hidden.

![accountmng-1](https://user-images.githubusercontent.com/33302775/41360081-e83913e6-6ef9-11e8-9119-6c1a96cb2d18.png)

**Comment by jobisoft** [comment]
Ok, that looks loke the additional folders are not announced via exchange active sync. If that is the case, there is nothing i can do. 

Try the following (in that order!)
- activate debug logging under help in the tbsync account manager
- disable your account
- restart thunderbird
- activate your account
- after the initial sync has finished go yo help again and open the debug log
- somewheren in that log there will be a list of all folders anounced by your server

If your additional folders do not show up there, tbsync cannot see them. If they DO show up, i need that list, because than tbsync ignores them, which would be a bug.

**Comment by freedriven** [comment]
Nope, the name of the additional folder does not appear in the debug log. I'll reach out to Zoho. Zoho responds, but usually after a few days.

Thanks for your quick help and great app!

**Comment by freedriven** [comment]
Update, Zoho responded to my question, and they confirmed..."Currently when you sync your calendar using exchange active sync , we will only sync the primary calendar."
Bummer...but...I can manage. 
Thanks again for your quick responses and great app.
