### ISSUE TITLE
[Little feature request] Being able to rename account

### ISSUE THREAD

**Issue by ldmpub** [jobisoft/TbSync#91]
[x] Yes, I have installed the latest available (beta) version from https://github.com/jobisoft/TbSync/releases and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
To be able to rename an account after setup in the "TbSync Account Manager" dialog.

## Suggestion
**Maybe contextual menu after right click on the current account name is the best place**.
Among existing options in this menu (like: Synchronize account, Delete account, ...) **add a new menu "Rename account".**

Thanks for your attention to this request,

**Comment by jobisoft** [comment]
Just disable the account and you can rename it.

**Comment by ldmpub** [comment]
Thanks for your very fast answer!

Operations described are not obvious but they are effective => issue closed.

Many thanks for this great piece of software I have just discovered but I already love ;-).

**Comment by jobisoft** [comment]
UserInterface is always difficult :-) I tried to be intuitive as much as possible. All settings are locked while the account is connected, but you can view all settings by using the small slider below the folders list. In that view mode, the main button is labeld "disconnect to edit".

But you have to find the slider first ...

I keep this in mind and will try to make it more obvious, that you have to disable the account in order to edit its settings.

**Comment by jobisoft** [comment]
I send you an invite, please restrict yourself to editing the wiki (i cannot define permissions for the wiki only)
